version: 2

models:

    - name: sales
      tests:
        - unique:
            column_name: "(orders_id || '-' || products_id)"
            
      columns:
          - name: orders_id
            description: Key, gz_raw_data.raw_gz_sales.orders_id
            tests : 
            - not_null 

          - name: products_id
            description: Key, gz_raw_data.raw_gz_sales.pdt_id
            tests : 
            - not_null

          - name: qty
            description: gz_raw_data.raw_gz_sales.quantity

          - name: turnover
            description: gz_raw_data.raw_gz_sales.revenue
            tests : 
            - not_null

          - name: purchase_cost
            description: gz_raw_data.raw_gz_product.purchSE_PRICE
            tests : 
            - not_null

          - name: margin
            description: gz_raw_data.raw_gz_sales.revenue - gz_raw_data.raw_gz_sales.quantity*gz_raw_data.raw_gz_product.purchSE_PRICE